// <copyright file="Types.cs" company="OpenClaw.Sdk">
// .NET port of the OpenClaw Python SDK (github.com/masteryodaa/openclaw-sdk)
// </copyright>

namespace OpenClaw.Sdk;

// ── Enums ─────────────────────────────────────────────────────────────────

public enum EventType
{
    // SDK-level
    Thinking,
    ToolCall,
    ToolResult,
    FileGenerated,
    Content,
    Error,
    Done,
    // Gateway push events
    Agent,
    Chat,
    Presence,
    Health,
    Tick,
    Heartbeat,
    Cron,
    Shutdown,
}

public enum AgentStatus { Created, Running, Idle, Error, Deleted }

public enum GatewayMode { Local, Protocol, OpenAiCompat, Auto }

// ── Core record types ──────────────────────────────────────────────────────

/// <summary>A single text/thinking content block from the gateway.</summary>
public sealed record ContentBlock(string Type, string? Text, string? Thinking)
{
    public string Value => Text ?? Thinking ?? string.Empty;
}

/// <summary>Token usage counters from an agent run.</summary>
public sealed record TokenUsage(int Input = 0, int Output = 0, int CacheRead = 0, int CacheWrite = 0, int TotalTokens = 0)
{
    public int Total => TotalTokens > 0 ? TotalTokens : Input + Output;

    public static TokenUsage FromGateway(System.Text.Json.JsonElement el)
    {
        int inp = el.TryGetProperty("input", out var i) ? i.GetInt32() : 0;
        int out_ = el.TryGetProperty("output", out var o) ? o.GetInt32() : 0;
        int total = el.TryGetProperty("totalTokens", out var t) ? t.GetInt32() : inp + out_;
        int cr = el.TryGetProperty("cacheRead", out var cr_) ? cr_.GetInt32() : 0;
        int cw = el.TryGetProperty("cacheWrite", out var cw_) ? cw_.GetInt32() : 0;
        return new(inp, out_, cr, cw, total);
    }
}

/// <summary>A file generated by the agent during execution.</summary>
public sealed record GeneratedFile(string Name, string Path, long SizeBytes, string MimeType);

/// <summary>A tool call made by the agent.</summary>
public sealed record ToolCallRecord(string Tool, string Input, string? Output, int? DurationMs);

/// <summary>The final result of an agent execution.</summary>
public sealed record ExecutionResult(
    bool Success,
    string Content,
    IReadOnlyList<ContentBlock> ContentBlocks,
    IReadOnlyList<GeneratedFile> Files,
    IReadOnlyList<ToolCallRecord> ToolCalls,
    string? Thinking,
    int LatencyMs,
    TokenUsage TokenUsage,
    DateTimeOffset CompletedAt,
    string? StopReason,
    string? ErrorMessage)
{
    public bool HasFiles => Files.Count > 0;
}

/// <summary>A streaming event pushed by the gateway.</summary>
public sealed record StreamEvent(EventType EventType, IReadOnlyDictionary<string, object?> Data);

/// <summary>Health status reported by the gateway.</summary>
public sealed record HealthStatus(bool Healthy, double? LatencyMs, string? Version);

/// <summary>Summary of an agent returned by agents.list.</summary>
public sealed record AgentSummary(string AgentId, string? Name, AgentStatus Status);

/// <summary>Session information from sessions.resolve / sessions.list.</summary>
public sealed record SessionInfo(
    string Key,
    string? Kind = null,
    string? ChatType = null,
    string? SessionId = null,
    long? UpdatedAt = null,
    int? InputTokens = null,
    int? OutputTokens = null,
    int? TotalTokens = null,
    string? Model = null);
