namespace Ouroboros.CLI.Commands;

/// <summary>
/// Represents an autonomous thought generated by the agent.
/// </summary>
public sealed record AutonomousThought(
    Guid Id,
    string ActionType,
    string Content,
    DateTime Timestamp);