namespace Ouroboros.Application.Services;

/// <summary>
/// Represents a thought generated by the autonomous mind.
/// </summary>
public record Thought
{
    public DateTime Timestamp { get; init; }
    public string Prompt { get; init; } = "";
    public string Content { get; init; } = "";
    public ThoughtType Type { get; init; }
}