// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Ouroboros.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class AndroidBehaviorFeature : object, global::Xunit.IClassFixture<AndroidBehaviorFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Android Behavior", "    As an Android developer\n    I want the app to handle initialization failures " +
                "gracefully\n    So that users never see a purple screen crash", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "AndroidBehavior.feature"
#line hidden
        
        public AndroidBehaviorFeature(AndroidBehaviorFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
    #line hidden
#line 7
        await testRunner.GivenAsync("a fresh Android behavior context", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/AndroidBehavior.feature.ndjson", 21);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="CLI Executor successful initialization allows command execution")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Android Behavior")]
        [global::Xunit.TraitAttribute("Description", "CLI Executor successful initialization allows command execution")]
        public async global::System.Threading.Tasks.Task CLIExecutorSuccessfulInitializationAllowsCommandExecution()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CLI Executor successful initialization allows command execution", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 10
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 11
        await testRunner.GivenAsync("a CLI executor configured to succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 12
        await testRunner.WhenAsync("I initialize with database path \"/tmp/test.db\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 13
        await testRunner.ThenAsync("the executor should be initialized", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 14
        await testRunner.WhenAsync("I execute command \"help\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 15
        await testRunner.ThenAsync("the command result should contain \"Executed: help\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="CLI Executor failed initialization throws exception")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Android Behavior")]
        [global::Xunit.TraitAttribute("Description", "CLI Executor failed initialization throws exception")]
        public async global::System.Threading.Tasks.Task CLIExecutorFailedInitializationThrowsException()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CLI Executor failed initialization throws exception", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 17
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 18
        await testRunner.GivenAsync("a CLI executor configured to fail initialization", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 19
        await testRunner.WhenAsync("I attempt to initialize with database path \"/tmp/test.db\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 20
        await testRunner.ThenAsync("it should throw InvalidOperationException with message \"CliExecutor initializatio" +
                        "n failed\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="CLI Executor database failure allows fallback without database")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Android Behavior")]
        [global::Xunit.TraitAttribute("Description", "CLI Executor database failure allows fallback without database")]
        public async global::System.Threading.Tasks.Task CLIExecutorDatabaseFailureAllowsFallbackWithoutDatabase()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CLI Executor database failure allows fallback without database", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 22
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 23
        await testRunner.GivenAsync("a CLI executor configured to fail with database", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 24
        await testRunner.WhenAsync("I attempt to initialize with database path \"/tmp/test.db\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 25
        await testRunner.ThenAsync("it should throw InvalidOperationException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 26
        await testRunner.WhenAsync("I initialize without database", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 27
        await testRunner.ThenAsync("the executor should be initialized", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 28
        await testRunner.AndAsync("I should be able to execute commands", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="CLI Executor command execution without initialization fails")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Android Behavior")]
        [global::Xunit.TraitAttribute("Description", "CLI Executor command execution without initialization fails")]
        public async global::System.Threading.Tasks.Task CLIExecutorCommandExecutionWithoutInitializationFails()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CLI Executor command execution without initialization fails", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 30
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 31
        await testRunner.GivenAsync("an uninitialized CLI executor", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 32
        await testRunner.WhenAsync("I attempt to execute command \"help\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 33
        await testRunner.ThenAsync("it should throw InvalidOperationException with message \"Executor not initialized\"" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Activity normal lifecycle renders UI")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Android Behavior")]
        [global::Xunit.TraitAttribute("Description", "Activity normal lifecycle renders UI")]
        public async global::System.Threading.Tasks.Task ActivityNormalLifecycleRendersUI()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Activity normal lifecycle renders UI", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 36
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 37
        await testRunner.GivenAsync("a test main page activity", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 38
        await testRunner.WhenAsync("I call OnCreate", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 39
        await testRunner.AndAsync("I call OnStart", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
        await testRunner.AndAsync("I call OnResume", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
        await testRunner.ThenAsync("the activity state should be Resumed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 42
        await testRunner.AndAsync("the UI should be rendered", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 43
        await testRunner.AndAsync("the output should contain \"Ouroboros CLI v1.0\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 44
        await testRunner.AndAsync("the output should contain \">\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 45
        await testRunner.AndAsync("the CLI executor should be initialized", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Activity initialization failure still renders UI")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Android Behavior")]
        [global::Xunit.TraitAttribute("Description", "Activity initialization failure still renders UI")]
        public async global::System.Threading.Tasks.Task ActivityInitializationFailureStillRendersUI()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Activity initialization failure still renders UI", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 47
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 48
        await testRunner.GivenAsync("a test main page activity configured to fail initialization", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 49
        await testRunner.WhenAsync("I call OnCreate", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 50
        await testRunner.AndAsync("I call OnStart", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 51
        await testRunner.AndAsync("I call OnResume", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 52
        await testRunner.ThenAsync("the activity state should be Resumed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 53
        await testRunner.AndAsync("the UI should be rendered", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 54
        await testRunner.AndAsync("the output should contain \"Ouroboros CLI v1.0\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
        await testRunner.AndAsync("the output should contain \"⚠ Initialization error\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 56
        await testRunner.AndAsync("the output should contain \">\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
        await testRunner.AndAsync("the CLI executor should be initialized via fallback", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Activity background and foreground maintains state")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Android Behavior")]
        [global::Xunit.TraitAttribute("Description", "Activity background and foreground maintains state")]
        public async global::System.Threading.Tasks.Task ActivityBackgroundAndForegroundMaintainsState()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Activity background and foreground maintains state", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 59
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 60
        await testRunner.GivenAsync("a resumed activity with initial output", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 61
        await testRunner.WhenAsync("I call OnPause", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 62
        await testRunner.AndAsync("I call OnStop", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 63
        await testRunner.AndAsync("I call OnStart", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 64
        await testRunner.AndAsync("I call OnResume", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
        await testRunner.ThenAsync("the activity state should be Resumed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 66
        await testRunner.AndAsync("the output should match the initial output", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 67
        await testRunner.AndAsync("the UI should be rendered", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Activity execute command in resumed state succeeds")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Android Behavior")]
        [global::Xunit.TraitAttribute("Description", "Activity execute command in resumed state succeeds")]
        public async global::System.Threading.Tasks.Task ActivityExecuteCommandInResumedStateSucceeds()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Activity execute command in resumed state succeeds", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 69
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 70
        await testRunner.GivenAsync("a resumed activity", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 71
        await testRunner.WhenAsync("I execute command \"help\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 72
        await testRunner.ThenAsync("the command result should contain \"Executed: help\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Activity execute command not resumed throws exception")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Android Behavior")]
        [global::Xunit.TraitAttribute("Description", "Activity execute command not resumed throws exception")]
        public async global::System.Threading.Tasks.Task ActivityExecuteCommandNotResumedThrowsException()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Activity execute command not resumed throws exception", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 74
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 75
        await testRunner.GivenAsync("an activity in Started state", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 76
        await testRunner.WhenAsync("I attempt to execute command \"help\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 77
        await testRunner.ThenAsync("it should throw InvalidOperationException with message \"Activity must be in Resum" +
                        "ed state\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Activity destroy cleans up resources")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Android Behavior")]
        [global::Xunit.TraitAttribute("Description", "Activity destroy cleans up resources")]
        public async global::System.Threading.Tasks.Task ActivityDestroyCleansUpResources()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Activity destroy cleans up resources", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 79
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 80
        await testRunner.GivenAsync("a resumed activity", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 81
        await testRunner.WhenAsync("I call OnPause", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 82
        await testRunner.AndAsync("I call OnStop", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 83
        await testRunner.AndAsync("I call OnDestroy", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 84
        await testRunner.ThenAsync("the activity state should be Destroyed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 85
        await testRunner.AndAsync("the UI should not be rendered", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 86
        await testRunner.AndAsync("the CLI executor should not be initialized", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Activity configuration change recreates activity")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Android Behavior")]
        [global::Xunit.TraitAttribute("Description", "Activity configuration change recreates activity")]
        public async global::System.Threading.Tasks.Task ActivityConfigurationChangeRecreatesActivity()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Activity configuration change recreates activity", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 88
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 89
        await testRunner.GivenAsync("a resumed activity", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 90
        await testRunner.WhenAsync("I simulate configuration change", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 91
        await testRunner.ThenAsync("the new activity state should be Resumed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 92
        await testRunner.AndAsync("the new activity UI should be rendered", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 93
        await testRunner.AndAsync("the new activity CLI executor should be initialized", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Database failure when app starts shows error not purple screen")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Android Behavior")]
        [global::Xunit.TraitAttribute("Description", "Database failure when app starts shows error not purple screen")]
        public async global::System.Threading.Tasks.Task DatabaseFailureWhenAppStartsShowsErrorNotPurpleScreen()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Database failure when app starts shows error not purple screen", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 96
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 97
        await testRunner.GivenAsync("database initialization will fail with \"SQLite Error: unable to open database fil" +
                        "e\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 98
        await testRunner.WhenAsync("the app starts", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 99
        await testRunner.ThenAsync("the UI should render", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 100
        await testRunner.AndAsync("the app output should contain \"Ouroboros CLI v1.0\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 101
        await testRunner.AndAsync("the app output should contain \"⚠ Initialization error\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 102
        await testRunner.AndAsync("the app output should contain \"SQLite Error\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 103
        await testRunner.AndAsync("the app output should contain \">\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="All services healthy provides full functionality")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Android Behavior")]
        [global::Xunit.TraitAttribute("Description", "All services healthy provides full functionality")]
        public async global::System.Threading.Tasks.Task AllServicesHealthyProvidesFullFunctionality()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("All services healthy provides full functionality", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 105
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 106
        await testRunner.GivenAsync("all services are healthy", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 107
        await testRunner.WhenAsync("the app starts", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 108
        await testRunner.ThenAsync("full functionality should be available", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 109
        await testRunner.AndAsync("the output should not contain \"⚠\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 110
        await testRunner.AndAsync("the app output should contain \"Ouroboros CLI v1.0\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 111
        await testRunner.AndAsync("the app output should contain \">\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Partial service failure enables degraded mode")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Android Behavior")]
        [global::Xunit.TraitAttribute("Description", "Partial service failure enables degraded mode")]
        public async global::System.Threading.Tasks.Task PartialServiceFailureEnablesDegradedMode()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Partial service failure enables degraded mode", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 113
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 114
        await testRunner.GivenAsync("primary service fails but fallback succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 115
        await testRunner.WhenAsync("the app starts", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 116
        await testRunner.ThenAsync("degraded mode should work", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 117
        await testRunner.AndAsync("the CLI executor should be available via fallback", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 118
        await testRunner.AndAsync("the app output should contain \"⚠ Initialization error\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 119
        await testRunner.AndAsync("the app output should contain \">\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Various initialization errors are displayed")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Android Behavior")]
        [global::Xunit.TraitAttribute("Description", "Various initialization errors are displayed")]
        [global::Xunit.InlineDataAttribute("SQLite Error: unable to open database file", "14", new string[0])]
        [global::Xunit.InlineDataAttribute("Permission denied", "15", new string[0])]
        [global::Xunit.InlineDataAttribute("Network unavailable", "16", new string[0])]
        [global::Xunit.InlineDataAttribute("Service initialization timeout", "17", new string[0])]
        public async global::System.Threading.Tasks.Task VariousInitializationErrorsAreDisplayed(string error_Message, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("error_message", error_Message);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Various initialization errors are displayed", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 121
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 122
        await testRunner.GivenAsync(string.Format("initialization will fail with \"{0}\"", error_Message), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 123
        await testRunner.WhenAsync("the app starts", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 124
        await testRunner.ThenAsync(string.Format("the specific error \"{0}\" should be shown to user", error_Message), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 125
        await testRunner.AndAsync("the app output should contain \"Ouroboros CLI v1.0\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 126
        await testRunner.AndAsync("the app output should contain \">\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Purple screen bug fix ensures UI always renders")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Android Behavior")]
        [global::Xunit.TraitAttribute("Description", "Purple screen bug fix ensures UI always renders")]
        public async global::System.Threading.Tasks.Task PurpleScreenBugFixEnsuresUIAlwaysRenders()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "18";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Purple screen bug fix ensures UI always renders", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 135
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 136
        await testRunner.GivenAsync("the purple screen bug is fixed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 137
        await testRunner.WhenAsync("initialization throws an exception", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 138
        await testRunner.ThenAsync("the UI must render", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 139
        await testRunner.AndAsync("the error must be shown to user", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 140
        await testRunner.AndAsync("the app should not show purple screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await AndroidBehaviorFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await AndroidBehaviorFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
